### ISSUE TITLE
HttpGet function causes "panic: sync: inconsistent mutex state" in macOS Catalina

### ISSUE THREAD

**Issue by marvelph** [gliderlabs/sigil#48]
Hello.

With Sigil v0.4.0, the following template seems to crash on macOS Catalina.
```
$ cat test.tmpl
{{ "http://www.google.com/" | httpget }}
```

The output is as follows.
```
$ sigil -f test.tmpl 

panic: sync: inconsistent mutex state

goroutine 10 [running]:
sync.(*Mutex).Lock(0xc820012140)
	/usr/local/go/src/sync/mutex.go:74 +0x16d
math/rand.(*lockedSource).Int63(0xc820012140, 0x0)
	/usr/local/go/src/math/rand/rand.go:239 +0x28
math/rand.(*Rand).Int63(0xc8200103f0, 0x5d115)
	/usr/local/go/src/math/rand/rand.go:46 +0x39
math/rand.(*Rand).Int(0xc8200103f0, 0x0)
	/usr/local/go/src/math/rand/rand.go:56 +0x21
math/rand.Int(0xc82002c070)
	/usr/local/go/src/math/rand/rand.go:183 +0x23
net.exchange(0xc820011870, 0xe, 0xc820011790, 0xf, 0xc82001001c, 0x12a05f200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:143 +0x3ec
net.tryOneName(0xc820016280, 0xc820011790, 0xf, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dnsclient_unix.go:176 +0x425
net.goLookupIPOrder.func1(0xc820016280, 0xc820011770, 0xc82001a600, 0x1c)
	/usr/local/go/src/net/dnsclient_unix.go:452 +0x59
created by net.goLookupIPOrder
	/usr/local/go/src/net/dnsclient_unix.go:454 +0x3ba

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc820080090, 0xc82009c1c0, 0x0, 0xc82000b0e4, 0x4, 0xc8200127a0, 0x11, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:554 +0x663
net/http.(*Transport).RoundTrip(0xc820080090, 0xc82009c1c0, 0x2, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:228 +0x4ac
net/http.send(0xc82009c1c0, 0x8734b0, 0xc820080090, 0xc820012780, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0x62c8e0, 0xc82009c1c0, 0x16, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0x62c8e0, 0xc82009c1c0, 0x4e7d20, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Get(0x62c8e0, 0xc82000b0e4, 0x16, 0x11756, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:306 +0xaa
net/http.Get(0xc82000b0e4, 0x16, 0xc82000b0e4, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:281 +0x45
github.com/gliderlabs/sigil/builtin.HttpGet(0x329360, 0xc8200113b0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/gliderlabs/sigil/builtin/builtin.go:92 +0x13d
reflect.Value.call(0x3849c0, 0x4e79a8, 0x13, 0x43dac8, 0x4, 0xc820012720, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x3849c0, 0x4e79a8, 0x13, 0xc820012720, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0xb1
text/template.(*state).evalCall(0xc8200a5938, 0x3271e0, 0xc82000b080, 0x15, 0x3849c0, 0x4e79a8, 0x13, 0x873940, 0xc82000b230, 0xc82000b0fe, ...)
	/usr/local/go/src/text/template/exec.go:602 +0xb38
text/template.(*state).evalFunction(0xc8200a5938, 0x3271e0, 0xc82000b080, 0x15, 0xc82000b260, 0x873940, 0xc82000b230, 0xc820011370, 0x1, 0x1, ...)
	/usr/local/go/src/text/template/exec.go:475 +0x33d
text/template.(*state).evalCommand(0xc8200a5938, 0x3271e0, 0xc82000b080, 0x15, 0xc82000b230, 0x329360, 0xc8200113b0, 0x58, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:372 +0x1e9
text/template.(*state).evalPipeline(0xc8200a5938, 0x3271e0, 0xc82000b080, 0x15, 0xc820014730, 0x329360, 0xc8200113b0, 0x58)
	/usr/local/go/src/text/template/exec.go:345 +0x180
text/template.(*state).walk(0xc8200a5938, 0x3271e0, 0xc82000b080, 0x15, 0x8737f8, 0xc82000b290)
	/usr/local/go/src/text/template/exec.go:180 +0x135
text/template.(*state).walk(0xc8200a5938, 0x3271e0, 0xc82000b080, 0x15, 0x8738b0, 0xc82000b1d0)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*Template).Execute(0xc82000e540, 0x873888, 0xc8200509a0, 0x3271e0, 0xc82000b080, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:143 +0x2b6
github.com/gliderlabs/sigil.Execute(0xc820076fc0, 0x29, 0x229, 0xc82000b080, 0x7ffeefbffc79, 0x9, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gliderlabs/sigil/sigil.go:128 +0xee6
main.main()
	/go/src/github.com/gliderlabs/sigil/cmd/sigil.go:67 +0x5aa

goroutine 6 [select]:
net.lookupIPDeadline(0xc8200127a0, 0xe, 0xe7791f71e, 0x0, 0x62ca40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:109 +0x6a5
net.internetAddrList(0x441ab0, 0x3, 0xc8200127a0, 0x11, 0xe7791f71e, 0x0, 0x62ca40, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0x43fba8, 0x4, 0x441ab0, 0x3, 0xc8200127a0, 0x11, 0xe7791f71e, 0x0, 0x62ca40, 0x0, ...)
	/usr/local/go/src/net/dial.go:153 +0x466
net.(*Dialer).Dial(0xc820014410, 0x441ab0, 0x3, 0xc8200127a0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:209 +0x124
net.(*Dialer).Dial-fm(0x441ab0, 0x3, 0xc8200127a0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc820080090, 0x441ab0, 0x3, 0xc8200127a0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:499 +0x79
net/http.(*Transport).dialConn(0xc820080090, 0x0, 0xc82000b0e4, 0x4, 0xc8200127a0, 0x11, 0xc82001a238, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc820080090, 0x0, 0xc82000b0e4, 0x4, 0xc8200127a0, 0x11, 0xc82001a240)
	/usr/local/go/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:551 +0x265

goroutine 8 [chan receive]:
net.goLookupIPOrder(0xc8200127a0, 0xe, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:457 +0x444
net.lookupIP(0xc8200127a0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup_unix.go:73 +0x153
net.glob.func15(0x4e7c48, 0xc8200127a0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/hook.go:10 +0x4d
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:106 +0x71
internal/singleflight.(*Group).doCall(0x62bf50, 0xc8200147d0, 0xc8200127a0, 0xe, 0xc820012800)
	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ed

goroutine 9 [runnable]:
net.dialUDP(0x441c68, 0x3, 0x0, 0xc8200ce000, 0xe7791f717, 0xc81ba3ce40, 0x62ca40, 0xc8200cc010, 0x0, 0x0)
	/usr/local/go/src/net/udpsock_posix.go:196 +0x45a
net.dialSingle(0xc8200ca080, 0x873988, 0xc8200ce000, 0xe7791f717, 0x1ba3ce40, 0x62ca40, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:367 +0x815
net.dialSerial.func1(0xe7791f717, 0x1ba3ce40, 0x62ca40, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:336 +0x75
net.dial(0x441c68, 0x3, 0x873988, 0xc8200ce000, 0xc8200b7828, 0xe7791f717, 0x1ba3ce40, 0x62ca40, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:40 +0x60
net.dialSerial(0xc8200ca080, 0xc8200cc010, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:338 +0x760
net.(*Dialer).Dial(0xc8200b7cb8, 0x441c68, 0x3, 0xc8200c8000, 0x1d, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:232 +0x50f
net.(*Dialer).dialDNS(0xc8200b7cb8, 0x441c68, 0x3, 0xc8200c8000, 0x1d, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:110 +0x144
net.exchange(0xc8200c8000, 0x1d, 0xc820011790, 0xf, 0xc8200c0001, 0x12a05f200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:135 +0x25a
net.tryOneName(0xc820016280, 0xc820011790, 0xf, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dnsclient_unix.go:176 +0x425
net.goLookupIPOrder.func1(0xc820016280, 0xc820011770, 0xc82001a600, 0x1)
	/usr/local/go/src/net/dnsclient_unix.go:452 +0x59
created by net.goLookupIPOrder
	/usr/local/go/src/net/dnsclient_unix.go:454 +0x3ba
```

**Comment by josegonzalez** [comment]
This no longer appears to be the case with the latest golang release. Please comment if you are still seeing this issue.
